# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/buoi8_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Application Configuration
spring.application.name=NguyenGiaHuyBuoi_8
spring.thymeleaf.cache=false
spring.main.allow-circular-references=true
